apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/part-of: prompthub
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: kustomize
