apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prompthub
resources:
  - ../../base
  - gateway-ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/instance: ec2-kubeadm
    includeSelectors: false
    includeTemplates: true
