apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app.kubernetes.io/name: discovery
    app.kubernetes.io/part-of: prompthub
    app.kubernetes.io/component: platform
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: discovery
  ports:
    - name: http
      port: 8761
      targetPort: http
      protocol: TCP
