apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-local-pv
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: prompthub
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/managed-by: kustomize
    prompthub.io/volume: kafka
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/prompthub/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: prompthub.io/node-pool
              operator: In
              values:
                - application
