spring:
  application:
    name: order-service
  config:
    import: optional:file:.env[.properties]
  sql:
    init:
      mode: always
  profiles:
    default: local

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/prompthub}
    username: ${DB_USERNAME:chan}
    password: ${DB_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: com.prompthub.order.*
    listener:
      ack-mode: manual

  cloud:
    openfeign:
      client:
        config:
          product-service:
            connect-timeout: ${PRODUCT_SERVICE_CONNECT_TIMEOUT_MS:2000}
            read-timeout: ${PRODUCT_SERVICE_READ_TIMEOUT_MS:3000}

server:
  port: 8080

#prompthub:
#  clients:
#    product-service:
#      url: ${PRODUCT_SERVICE_URL:http://localhost:8081}

prompthub:
  grpc:
    product:
      host: ${PRODUCT_GRPC_HOST:localhost}
      port: ${PRODUCT_GRPC_PORT:9092}
      deadline-ms: ${PRODUCT_GRPC_DEADLINE_MS:2000}
  outbox-relay:
    enabled: true
    fixed-delay-ms: 5000
    batch-size: 100
    max-retry-count: 3

logging:
  level:
    com.prompthub.order: debug
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: default | local

  cloud:
    compatibility-verifier:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: test

  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    url: jdbc:h2:mem:prompthub_order_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

prompthub:
  outbox-relay:
    enabled: false

logging:
  level:
    com.prompthub.order: debug
