apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-service
  labels:
    app.kubernetes.io/name: admin-service
    app.kubernetes.io/part-of: prompthub
    app.kubernetes.io/component: service
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: true
