apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
    app.kubernetes.io/name: apigateway
    app.kubernetes.io/part-of: prompthub
    app.kubernetes.io/component: gateway
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: apigateway
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
