server:
  port: 18081

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=user_service
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      enable-auto-commit: false

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  access-token-expire-seconds: 3600
  refresh-token-expire-seconds: 2592000

grpc:
  server:
    port: ${USER_GRPC_SERVER_PORT}
  client:
    product-service:
      address: 'static://product-service:${PRODUCT_GRPC_SERVER_PORT}'
      negotiation-type: plaintext

user:
  kafka:
    consumer:
      settlement:
        topic: settlement-events
    listener:
      settlement:
        enabled: false   # 통합 검증 시 true
