server:
  port: 8761

spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  structured:
    format:
      console: logstash
    json:
      add:
        serviceName: ${spring.application.name}
  level:
    root: INFO
