apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  labels:
    app.kubernetes.io/part-of: prompthub
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: kustomize
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
